---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rebrain-cluster
  region: us-east-1
  version: "1.22"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  instanceType: t3.small
  # spot: true
  ssh:
    enableSsm: true

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:us-east-1:216287962757:key/01296fc1-59d8-436e-9399-837ea71e2ffb
